# Generated by Django 2.0.1 on 2018-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypto_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='eth_address'),
        ),
    ]
