# Generated by Django 2.0.1 on 2018-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180124_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='onfidocall',
            name='onfido_id',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onfidocall',
            name='type',
            field=models.CharField(choices=[('applicant', 'applicant'), ('check', 'check'), ('webhook', 'webhook')], max_length=20),
        ),
    ]
