# Generated by Django 2.0.1 on 2018-01-29 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180125_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='non_us_resident',
            field=models.BooleanField(default=False, verbose_name='I am not a US resident'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='I accept the <a href="/static/Token Sale T&Cs.pdf">Terms and Conditions</a>'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^(0x)?[0-9a-fA-F]{40}$', "Enter a valid ethereum address, example: '0x4a4ac8d0b6a2f296c155c15c2bcaf04641818b78'", 'invalid')], verbose_name='ETH address'),
        ),
    ]
