# Generated by Django 2.0.1 on 2018-01-30 10:39

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180129_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_contrib',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Accepted format is YYYY-MM-DD', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^(0x)?[0-9a-fA-F]{40}$', "Enter a valid ethereum address, example: '0x4a4ac8d0b6a2f296c155c15c2bcaf04641818b78'", 'invalid')], verbose_name='Your ETH wallet address from which you’ll be sending your contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
    ]
