# Generated by Django 2.0.1 on 2018-01-30 10:39

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180130_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eth_contrib',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
