# Generated by Django 2.0.1 on 2018-01-31 21:48

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180130_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(help_text='Accepted format is YYYY-MM-DD', null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='building_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^(0x)?[0-9a-fA-F]{40}$', "Enter a valid ethereum address, example: '0x4a4ac8d0b6a2f296c155c15c2bcaf04641818b78'", 'invalid')], verbose_name='Your ETH wallet address from which you’ll be sending your contribution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='proof_of_address_file',
            field=models.FileField(null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='proof_of_address', verbose_name='Proof of address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
    ]
